plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

task buildGoMobile(type: Exec) {
    workingDir '../go-core'

    def outputAar = "${project.projectDir}/libs/gobackend.aar"

    executable '/Users/antilopa/go/bin/gomobile'
    args 'bind', '-v', '-target=android', '-androidapi=21', '-o', outputAar, './pkg/mobile'

    doFirst {
        mkdir "${project.projectDir}/libs"
    }
}

android {
    namespace 'com.securemessenger'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "com.securemessenger"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    buildFeatures {
        compose true
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.activity.compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.graphics
    implementation libs.androidx.compose.ui.tooling.preview

    implementation libs.androidx.compose.material3
    implementation libs.androidx.compose.material.icons.extended

    implementation libs.androidx.navigation.compose

    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

    testImplementation libs.junit

    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.compose.ui.test.junit4

    debugImplementation libs.androidx.compose.ui.tooling
    debugImplementation libs.androidx.compose.ui.test.manifest
}

tasks.withType(JavaCompile) {
    compileTask -> compileTask.dependsOn buildGoMobile
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
    kotlinTask -> kotlinTask.dependsOn buildGoMobile
}