// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: protocol/messenger.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_protocol_messenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_protocol_messenger_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_protocol_messenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_protocol_messenger_proto_rawDescGZIP(), []int{1}
}

func (x *ChallengeResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // Подпись nonce из ChallengeResponse
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_protocol_messenger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messenger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_protocol_messenger_proto_rawDescGZIP(), []int{2}
}

func (x *AuthRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AuthRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuthRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_protocol_messenger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messenger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_protocol_messenger_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_protocol_messenger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messenger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_protocol_messenger_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type MessagePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"` // Кому доставить
	SenderNodeId  string                 `protobuf:"bytes,2,opt,name=sender_node_id,json=senderNodeId,proto3" json:"sender_node_id,omitempty"` // От кого
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                 // Слой 3 (зашифрованный и подписанный отправителем)
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                             // Подпись Слоя 4 (для сервера)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePacket) Reset() {
	*x = MessagePacket{}
	mi := &file_protocol_messenger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePacket) ProtoMessage() {}

func (x *MessagePacket) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messenger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePacket.ProtoReflect.Descriptor instead.
func (*MessagePacket) Descriptor() ([]byte, []int) {
	return file_protocol_messenger_proto_rawDescGZIP(), []int{5}
}

func (x *MessagePacket) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *MessagePacket) GetSenderNodeId() string {
	if x != nil {
		return x.SenderNodeId
	}
	return ""
}

func (x *MessagePacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MessagePacket) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_protocol_messenger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messenger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_protocol_messenger_proto_rawDescGZIP(), []int{6}
}

func (x *SendResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *SendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protocol_messenger_proto protoreflect.FileDescriptor

const file_protocol_messenger_proto_rawDesc = "" +
	"\n" +
	"\x18protocol/messenger.proto\x12\x0fsecuremessenger\"+\n" +
	"\x10ChallengeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\")\n" +
	"\x11ChallengeResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"c\n" +
	"\vAuthRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"3\n" +
	"\fAuthResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"7\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"\x93\x01\n" +
	"\rMessagePacket\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\x12$\n" +
	"\x0esender_node_id\x18\x02 \x01(\tR\fsenderNodeId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"B\n" +
	"\fSendResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xce\x02\n" +
	"\tMessenger\x12U\n" +
	"\fGetChallenge\x12!.securemessenger.ChallengeRequest\x1a\".securemessenger.ChallengeResponse\x12K\n" +
	"\fAuthenticate\x12\x1c.securemessenger.AuthRequest\x1a\x1d.securemessenger.AuthResponse\x12P\n" +
	"\tSubscribe\x12!.securemessenger.SubscribeRequest\x1a\x1e.securemessenger.MessagePacket0\x01\x12K\n" +
	"\n" +
	"SendPacket\x12\x1e.securemessenger.MessagePacket\x1a\x1d.securemessenger.SendResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_protocol_messenger_proto_rawDescOnce sync.Once
	file_protocol_messenger_proto_rawDescData []byte
)

func file_protocol_messenger_proto_rawDescGZIP() []byte {
	file_protocol_messenger_proto_rawDescOnce.Do(func() {
		file_protocol_messenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_messenger_proto_rawDesc), len(file_protocol_messenger_proto_rawDesc)))
	})
	return file_protocol_messenger_proto_rawDescData
}

var file_protocol_messenger_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protocol_messenger_proto_goTypes = []any{
	(*ChallengeRequest)(nil),  // 0: securemessenger.ChallengeRequest
	(*ChallengeResponse)(nil), // 1: securemessenger.ChallengeResponse
	(*AuthRequest)(nil),       // 2: securemessenger.AuthRequest
	(*AuthResponse)(nil),      // 3: securemessenger.AuthResponse
	(*SubscribeRequest)(nil),  // 4: securemessenger.SubscribeRequest
	(*MessagePacket)(nil),     // 5: securemessenger.MessagePacket
	(*SendResponse)(nil),      // 6: securemessenger.SendResponse
}
var file_protocol_messenger_proto_depIdxs = []int32{
	0, // 0: securemessenger.Messenger.GetChallenge:input_type -> securemessenger.ChallengeRequest
	2, // 1: securemessenger.Messenger.Authenticate:input_type -> securemessenger.AuthRequest
	4, // 2: securemessenger.Messenger.Subscribe:input_type -> securemessenger.SubscribeRequest
	5, // 3: securemessenger.Messenger.SendPacket:input_type -> securemessenger.MessagePacket
	1, // 4: securemessenger.Messenger.GetChallenge:output_type -> securemessenger.ChallengeResponse
	3, // 5: securemessenger.Messenger.Authenticate:output_type -> securemessenger.AuthResponse
	5, // 6: securemessenger.Messenger.Subscribe:output_type -> securemessenger.MessagePacket
	6, // 7: securemessenger.Messenger.SendPacket:output_type -> securemessenger.SendResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_messenger_proto_init() }
func file_protocol_messenger_proto_init() {
	if File_protocol_messenger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_messenger_proto_rawDesc), len(file_protocol_messenger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_messenger_proto_goTypes,
		DependencyIndexes: file_protocol_messenger_proto_depIdxs,
		MessageInfos:      file_protocol_messenger_proto_msgTypes,
	}.Build()
	File_protocol_messenger_proto = out.File
	file_protocol_messenger_proto_goTypes = nil
	file_protocol_messenger_proto_depIdxs = nil
}
